# Generated by Django 3.1 on 2020-08-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('youtube_code', models.CharField(max_length=200)),
                ('info', models.TextField()),
                ('rating', models.CharField(max_length=5)),
                ('client', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('time', models.IntegerField()),
                ('p1', models.TextField()),
                ('p2', models.TextField()),
                ('p3', models.TextField()),
            ],
        ),
    ]
