# Generated by Django 3.1 on 2020-09-03 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200903_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='resume',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
