# Generated by Django 3.1 on 2020-09-03 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_qualities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certificates',
            new_name='Certificate',
        ),
        migrations.RenameModel(
            old_name='Qualities',
            new_name='Qualitie',
        ),
    ]
