# Generated by Django 3.1 on 2020-09-04 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_skill_md'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='md',
            new_name='lg',
        ),
    ]
