# Generated by Django 3.1 on 2020-09-04 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200904_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='icon',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
